<?php
/**
 * Box Sizes for fedex in array format
 */

return array(
	array(
		'name' => 'Mini-Case',
		'id' => 'Mini-Case',
		'max_weight' => 25,
		'box_weight' => 0,
		'length'=>10,
		'width'=>10,
		'height'=>8,
	),
	array(
		'name' => 'HS-Case',
		'id' => 'HS-Case',
		'max_weight'=>18.5,
		'box_weight' => 0,
 		'length'=>10,
		'width'=>10,
		'height'=>8,
	),
	array(
		'name' => 'ST-Case',
		'id' => 'ST-Case',
		'max_weight' =>14,
		'box_weight' => 0,
		'length'=>10,
		'width'=>10,
		'height'=>8,
	),
	array(
		'name' => 'CH-Case',
		'id' => 'CH-Case',
		'max_weight'=>40,
		'box_weight' => 0,
		'length'=>14,
		'width'=>14,
		'height'=>7,
	),
	array(
		'name' => 'BS-Case',
		'id' => 'BS-Case',
		'max_weight'=>60,
		'box_weight' => 0,
		'length'=>14,
		'width'=>14,
		'height'=>9,
	),
	array(
		'name' => 'Cartridges5',
		'id' => 'Cartridges_5',
		'max_weight'=>4.014,
		'box_weight' => 0,
 		'length'=>6,
		'width'=>4,
		'height'=>4,
	),
	array(
		'name' => 'Cartridges6',
		'id' => 'Cartridges_6',
		'max_weight'=>7.136,
		'box_weight' => 0,
 		'length'=>6,
		'width'=>6,
		'height'=>6,
	),
	array(
		'name' => 'Cartridges large formate',
		'id' => 'Cartridges3',
		'max_weight'=>13.5,
		'box_weight' => 0,
 		'length'=>6,
		'width'=>6,
		'height'=>6,
	),
	array(
		'name' => 'Large Format Magazine Single',
		'id' => 'MagazineSingle',
		'max_weight'=>4,
		'box_weight' => 0,
 		'length'=>6,
		'width'=>6,
		'height'=>6,
	),
	array(
		'name' => 'Large Format Magazine Double',
		'id' => 'MagazineDouble',
		'max_weight'=>8,
		'box_weight' => 0,
 		'length'=>6,
		'width'=>6,
		'height'=>6,
	),
	array(
		'name' => 'Cleaning-Kit',
		'id' => 'Cleaning-Kit',
		'max_weight'=>2,
		'box_weight' => 0,
		'length'=>12,
		'width'=>6,
		'height'=>4,
	),
	array(
		'name' => 'Launcher',
		'id' => 'Launcher',
		'max_weight'=>5,
		'box_weight' => 0,
		'length'=>13,
		'width'=>10,
		'height'=>4,
	),
	array(
		'name' => 'Double-Launcher',
		'id' => 'Double-Launcher',
		'max_weight'=>20,
		'box_weight' => 0,
		'length'=>14,
		'width'=>12,
		'height'=>11,		
	),
	array(
		'name' => 'IAK',
		'id' => 'IAK',
		'max_weight'=>20,
		'box_weight' => 0,
		'length'=>16,
		'width'=>12,
		'height'=>12,
	),
	array(
		'name' => 'Double-IAK',
		'id' => 'Double-IAK',
		'max_weight'=>40,
		'box_weight' => 0,
		'length'=>20,
		'width'=>16,
		'height'=>15,		
	),
	array(
		'name' => 'LF-Launcher',
		'id' => 'LF-Launcher',
		'max_weight'=>15,
		'box_weight' => 0,
		'length'=>6,
		'width'=>13,
		'height'=>37,
	),
	array(
		'name' => 'LF-Flares-Full-Case',
		'id' => 'LF-Flares-Full-Case',
		'max_weight'=>40,
		'box_weight' => 0,
		'length'=>14,
		'width'=>14,
		'height'=>11,
	)
);



